### ISSUE TITLE
I got 'unknown namespace' error when edit node client-ltp,can anyone help me with this?

### ISSUE THREAD

**Issue by pezou** [OpenNetworkingFoundation/CENTENNIAL#16]
It's a leafref of '/core-model:network-element/core-model:ltp/core-model:uuid'  in core-model.yang;
when i trying to commit to running database after edit it's value, the following error arising:
> \>merge target=/network-element/ltp[uuid='LTP-MWPS-TTP-RADIO']/client-ltp value="LTP-MWS-RADIO"
RPC OK Reply 21 for session 1:

>\> xget-config /network-element/ltp[uuid='LTP-MWPS-TTP-RADIO']/client-ltp source=candidate
RPC Data Reply 22 for session 1:
rpc-reply {
  data {
    network-element {
      ltp LTP-MWPS-TTP-RADIO {
        uuid LTP-MWPS-TTP-RADIO
        client-ltp LTP-MWS-RADIO
      }
    }
  }
}

>\>  xget-config /network-element/ltp[uuid='LTP-MWPS-TTP-RADIO']/client-ltp source=running
RPC Data Reply 23 for session 1:
rpc-reply {
  data {
  }
}

> \> commit
RPC Error Reply 24 for session 1:
rpc-reply {
  rpc-error {
    error-type application
    error-tag **unknown-namespace**
    error-severity error
    error-app-tag data-invalid
    **error-path /core-model:network-element/core-model:ltp[core-model:uuid='LTP-MWPS-TTP-RADIO']/core-model:client-ltp
    error-message 'unknown namespace'**
    error-info {
      error-number 266
    }
  }
}

**Comment by pezou** [comment]
I change the path in core-model.yang,
from:

**Comment by pezou** [comment]
I remove the prefix in the leafref path, and rebuild the core-model. then everything works fine.
Did I missed some configuration of netconf, or the leafref path prefix is superfluous?

before:
> leaf-list client-ltp {
	type leafref {
		path **'/core-model:network-element/core-model:ltp/core-model:uuid';**
	}
	description "References contained LTPs representing client traffic of this LTP for normal cases of multiplexing.";
}

after:
> leaf-list client-ltp {
	type leafref {
		path **'/network-element/ltp/uuid';**
	}
	description "References contained LTPs representing client traffic of this LTP for normal cases of multiplexing.";
}

**Comment by demx8as6** [comment]
@pezou Hi, this is very interesting information!!! ... but my require input from additional people form other projects (ONF Eagle, OpenYuma, ....). Could you please describ a bit about your use case and which NetConf-Server frame work is involved? 

regarding your finding: The prefix is generated by the ONF/Eagle/UmlYangTools based on the ONF-UML-YANG-Mapping document. At this moment I cant tell you whether your solution may cause issues elsewhere...

**Comment by pezou** [comment]
It's openyuma with default config.
I am just initializing the container network-element.

**Comment by alexandrustancu** [comment]
Hello,

I've tried also what @pezou described and I get the same "unknown namespace" error on my OpenYuma installation as well. I assume it is not necessarily an OpenYuma bug, but some expected behavior.

I've tried another workaround as well: changing the namespace of the core-model.yang from **_CoreModel_** to **_core-model_**, but I get the same error.

Defining the path in the _leafref_ types with the same prefix of the YANG module that we are already in seems to be the problem, as @pezou described, and for sure is redundant.

I don't know all the implications of changing this. The first that came to my mind (and I've already tested it, without having any issues) was to try and add a new **_layer-protocol_** in the microwave-model. Since layer-protocol is defined like this:

```
leaf-list logical-termination-point {
            type leafref {
                path '/core-model:network-element/core-model:ltp/core-model:uuid';
            }
            description "none";
        }
```
I thought we might have problems if we are referring the values from the core-model that I've changed. But there are no problems, I was able to add a new layer-protocol without any issues. And also, I was able to edit the values of **_client-ltp_** or **_server-ltp_** without any issues. It behaves exactly as expected, you are not able to put a value there without it to exist previously. So the checking of that _leafref_ to exist is done correctly.

I'm guessing that, as @pezou pointed out, we could just discard the prefixes from the paths of the _leafref_ types. Since they refer only to paths in the same YANG module, they seem redundant.

**Comment by demx8as6** [comment]
I'm going to remove the redundant prefixes ...

**Comment by demx8as6** [comment]
@pezou Please see modified [YANGs](https://github.com/OpenNetworkingFoundation/CENTENNIAL/tree/master/models/yang)
Could you please check - if possible please close the issue.

**Comment by pezou** [comment]
@demx8as6  thanks, it behaves as expected

**Comment by pezou** [comment]
@demx8as6 Except removing redundant prefix in core-model, grouping name in microwave-model.yang have been changed as well. It causes the SIL code changed and that may cost lots of time to synchronism.

I wonder which version of YANG files will be uesed in the TST, and which in POC4. Will the model change again?

**Comment by demx8as6** [comment]
@pezou The target is to use the same yang modules in TST and 4th PoC. Only Prio1 issues will because changes in the Yang modules. Both changes (grouping-names, prefixes) were Prio1 issues, because the limit the end-to-end functionality.

**Comment by pezou** [comment]
@demx8as6 OK,I get it.
